/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsProvidersIndexRouteImport } from './routes/settings/providers/index'
import { Route as SettingsProvidersProviderRouteImport } from './routes/settings/providers/provider'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersIndexRoute = SettingsProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersProviderRoute =
  SettingsProvidersProviderRouteImport.update({
    id: '/providers/provider',
    path: '/providers/provider',
    getParentRoute: () => SettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/settings/providers/provider': typeof SettingsProvidersProviderRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/providers/provider': typeof SettingsProvidersProviderRoute
  '/settings/providers': typeof SettingsProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/': typeof SettingsIndexRoute
  '/settings/providers/provider': typeof SettingsProvidersProviderRoute
  '/settings/providers/': typeof SettingsProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/settings'
    | '/settings/'
    | '/settings/providers/provider'
    | '/settings/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/settings'
    | '/settings/providers/provider'
    | '/settings/providers'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/settings'
    | '/settings/'
    | '/settings/providers/provider'
    | '/settings/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers/': {
      id: '/settings/providers/'
      path: '/providers'
      fullPath: '/settings/providers/'
      preLoaderRoute: typeof SettingsProvidersIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers/provider': {
      id: '/settings/providers/provider'
      path: '/providers/provider'
      fullPath: '/settings/providers/provider'
      preLoaderRoute: typeof SettingsProvidersProviderRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface SettingsRouteChildren {
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsProvidersProviderRoute: typeof SettingsProvidersProviderRoute
  SettingsProvidersIndexRoute: typeof SettingsProvidersIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsProvidersProviderRoute: SettingsProvidersProviderRoute,
  SettingsProvidersIndexRoute: SettingsProvidersIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
